### PR TITLE
Remove final for this class

### PR DESCRIPTION
**Pull request by nelsongomes**
This allows to extend this class and override some behaviours. My idea is to create class YankExtended that extends Yank and throws database errors up. Why? I do understand why you hide exceptions from code. But this stops anyone of creating more complex microservices, because if the database is down, I need to know it is down so I can put circuit breakers on the code. So to hide exceptions in all use cases in not definitely the best solution.

And I would remove final keyword, because it is limiting the possibility of others extending your work.

### CODE REVIEW

**Comment by timmolter** [comment]
Thanks, I agree. I was thinking of a different approach though. Please tell me what you think...

I was going to add a flag in the `Yank` class, something like `throwExceptions`, so the beahior would be configurable. The I would add a private method called `handleException` and the appropriate action would be taken :1) just log it or 2) throw it. The thrown exception would be an Unchecked exception.

What do you think?

**Comment by nelsongomes** [comment]
Both options are valid.

I like the possibility of specifying the exception behaviour, but I 
think it must be separate classes (or at least separate methods), 
because if a SQLException is thrown I want my code to be forced to catch 
it, so I don't have surprises in runtime.

I would add new methods that do exactly the same, but throw exceptions 
up, this way if a developer wants the majority of code to ignore 
exceptions he can, but if in a special case he wants to catch exceptions 
he also can. In practice you would blend the best of both worlds in 
slightly different methods giving the option to choose.


Thanks,
Nelson Gomes

Às 15:02 de 21/06/16, Tim Molter escreveu:

**Comment by nelsongomes** [comment]
I forgot one thing: do you want me to change the code and add the methods I talked about? and make a PR?

**Comment by timmolter** [comment]
Not yet. I need some more time to think about it. I don't really like the idea of duplicating every method, as I feel there must be a more elegant way.

If we went with my flag idea, you could just control on your end which thrown exceptions you wanted to handle and ignore, right?

**Comment by nelsongomes** [comment]
Yes, but I wouldn't use unchecked expections. I'm planning to make a presentation on microservices in October, but for my stuff to work I need to have exceptions running, can you at least approve this PR?

Nelson

**Comment by driverpt** [comment]
@timmolter, what about having a Template Method Design Pattern approach. There is a "Default" behaviour and the customisations are made through handlers or reimplementing some methods.

**Comment by nelsongomes** [comment]
What do I need to run tests? I've done some changes on my fork, if you're interested.

**Comment by timmolter** [comment]
`mvn clean package ` will run the tests. Cool, I'll check it out.

**Pull request merged**
