### PR TITLE
Expose access to underling DataSource. 

### PR DESCRIPTION
**Pull request by eepstein**
Example use case: calling a QueryRunner's insert() method to retrieve generated keys from the database.

### CODE REVIEW

**Comment by eepstein** [comment]
Second commit addresses Issue #15, https://github.com/timmolter/Yank/issues/15

**Comment by eepstein** [comment]
For Issue #7 , with access to the underlying DataSource, I found this work for single objects:

        return new QueryRunner(Yank.getDataSource(POOL_NAME))
                .insert(sql, (gk) -> {
                    if (gk.next()) {
                        return gk.getLong(1);
                    } else {
                        throw new SQLException("Inserting pull record failed, no generated key obtained.");
                    }
                }, params);

But it does use Java 8 lambda's

**Comment by timmolter** [comment]
@eepstein I added your new functionality manually. Thanks for the great new functionality!

**Comment by timmolter** [comment]
@eepstein Any idea how to do do the above code with Java 6?

**Comment by timmolter** [comment]
@eepstein I figured it out. Update pushed.

**Comment by eepstein** [comment]
AH.
Question about using the GenerousBeanProcessor.  Did you see that change ?

**Comment by timmolter** [comment]
Yeah, I added that manually too. Great find! See: https://github.com/timmolter/Yank/issues/15

**Comment by eepstein** [comment]
Ah, good good.

I was looking at one other thing.  I'm using HikariCP but configuring it via Yaml (DropWizard context).  So, the question was whether Yank would still work with a method that lets one add a configured DataSource rather than having it invoke the constructor ?

**Comment by timmolter** [comment]
I was originally trying to do that. That way, people could choose whatever dataSource they want.The problem is that there are no generic interface for shutting down a datasource. See `YankPoolManager.release()`.  But I could add an overloaded method to pass in a `HikariDataSource` like: acreatePool(String poolName, HikariDataSource hikariDataSource)`. Is that what you mean?

**Comment by eepstein** [comment]
Interesting.  I figured that’d be the (or a) problem.  Hmmm… Let me see if there’s a workaround.

In the meantime, yes a more general way of just adding a HikariCP would be welcome.
Also, should that Map that holds the ConnectionPools be a ConcurrentHashMap?  Not sure it really matters given use cases, but was wondering about Yank in multi-threaded situations.

**Comment by timmolter** [comment]
I'll work on a more general solution again. I'll look into the concurrency issue.

So is  `createPool(String poolName, HikariDataSource hikariDataSource)` sufficient for you?

**Comment by eepstein** [comment]
Wow.  That works for me.

Thanks!

**Comment by timmolter** [comment]
How are you configuring Hikari in DW? Are you passing in all the config props in the yml file?

**Comment by eepstein** [comment]
Hey,

So I just hacked on it this and got a Java 1.5 solution that allows a general DataSource (sort of).
I cribbed off of what HikariCP does and noticed that it implements both DataSource and Closable and followed suit with YankPoolManager using Generics.

/ Ezra

**Comment by eepstein** [comment]
That’s the intention.  I was trying to decide whether to go with the Properties approach (following Hikari)), or build a custom configurable factory with a #build() method, following what DropWizard has for JDBC.  Looks like the latter approach, though more tedious, is cleaner (less “automagical”).

**Comment by timmolter** [comment]
I just Create a `YankManager class` which reads the DB.properties file I build into the jar. See 

https://github.com/timmolter/XDropWizard/blob/master/src/main/java/com/xeiam/xdropwizard/manager/YankManager.java

and 

https://github.com/timmolter/XDropWizard/blob/master/xdropwizard.yml

You can also put placeholder value in the properties files to be replaced with real values during a Maven build, for say a test and prod deployment.

But your way would work too. Just different ways of doing things.

**Comment by eepstein** [comment]
Ah cool.  Thanks.

Here’s part of a Java 1.5 Generics way to support other DataSources and also the release() functionality:

	public final class YankPoolManager<T extends DataSource & Closeable> { 
        …
           private final Map<String, T> pools = ...
        ...
           protected void addDataSource(String name, T ds) {
              pools.put(name, ds);
           }

and then, inside #release() call close() inside a try block.

**Comment by eepstein** [comment]
I’m going with this.  I like the way it bridges both.  Plus, I already have the configs in a .properties file for both dev and prod envs.  

coolness.

**Pull request closed without merging**
